name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - appmode
  - pip:
    - pandas
    - fileupload
    - ipywidgets
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - markdown
    
